name: Makefile CI
on:
  push:
  workflow_dispatch:
    inputs:
      commitid:
        description: "commitid"
        required: false
        type: string
      debianversion:
        description: "debianversion"
        required: false
        type: string

env:
  commitid: bookworm-6.5
  debianversion: bookworm

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: set env
        run: |
          if [ ! '${{ inputs.patch }}' = '' ];
          then
            echo "patch=${{ inputs.patch }}" >> "${{ github.env }}"
          fi
          if [ ! '${{ inputs.commitid }}' = '' ];
          then
            echo "commitid=${{ inputs.commitid }}" >> "${{ github.env }}"
          fi
          if [ ! '${{ inputs.debianversion }}' = '' ];
          then
            echo "debianversion=${{ inputs.debianversion }}" >> "${{ github.env }}"
          fi

      - uses: actions/checkout@v4

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: debian:${{ env.debianversion }}
          options: -v ${{ github.workspace }}:/build
          run: |
            apt update
            apt install git wget -y
            echo "deb https://download.proxmox.com/debian/pve ${{ env.debianversion }} pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
            echo "deb https://download.proxmox.com/debian/devel bookworm main" >> /etc/apt/sources.list
            wget https://enterprise.proxmox.com/debian/proxmox-release-${{ env.debianversion }}.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-${{ env.debianversion }}.gpg
            apt update
            apt install devscripts -y
            cd build
            git clone git://git.proxmox.com/git/pve-kernel.git
            cd pve-kernel
            git reset --hard ${{ env.commitid }}
            # git submodule update --init
            # apt install dh-virtualenv dwarves libdw-dev libiberty-dev lz4 dh-python python3
            echo ---installed env---
            # apt list
            mk-build-deps --install --tool "apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y" debian/control
            make build-dir-fresh
            curl -OL https://github.com/srhse5rh/pve-rdtsc-patch-script/raw/master/patch.sh
            chmod +x patch.sh && ./patch.sh
            make deb

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          path: pve-kernel/*.deb
